import { Container } from '@mui/material';
import Head from 'next/head';
import React from 'react';
import Navigation from '../Navigation';

const Layout: React.FC<React.PropsWithChildren> = ({ children }) => (
  <>
    <Head>
      <title>Reach Quantity</title>
      <meta name="description" content="Generated by create next app"/>
      <meta name="viewport" content="width=device-width, initial-scale=1"/>
      <link rel="icon" href="/favicon.ico"/>
    </Head>
    <main>
      <Container>
        <Navigation/>
        {children}
      </Container>
    </main>
  </>
);

export default Layout;
