import Head from 'next/head';
import Link from 'next/link';
import React from 'react';
import styles from '../../styles/Home.module.css';

const Layout: React.FC<React.PropsWithChildren> = ({ children }) => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app"/>
      <meta name="viewport" content="width=device-width, initial-scale=1"/>
      <link rel="icon" href="/favicon.ico"/>
    </Head>
    <main className={styles.main}>
      <nav>
        <Link href="/create">Create New Target</Link>
        <Link href="/example">Example</Link>
      </nav>
      {children}
    </main>
  </>
);

export default Layout;
