import Head from 'next/head';
import React from 'react';
import styles from '../../styles/Home.module.css';
import Navigation from '../Navigation';

const Layout: React.FC<React.PropsWithChildren> = ({ children }) => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app"/>
      <meta name="viewport" content="width=device-width, initial-scale=1"/>
      <link rel="icon" href="/favicon.ico"/>
    </Head>
    <main className={styles.main}>
      <Navigation/>
      {children}
    </main>
  </>
);

export default Layout;
